### ISSUE TITLE
VNC Fullscreen and Send Keys not working

### ISSUE THREAD

**Issue by Bandic007** [retspen/webvirtcloud#174]
@catborise - after you changes didn't worked for me I was able to get the noVNC project from github and make it work in my setup. I have a separate "Send CtrlAltDel" button now, which is working, but the dropdown menu with the send alt+FN keys and fullscreen keys from the console-base.html are not working.
I guess it is something it they way those are being called from the html as I am getting:
`referenceError: sendCtrlAltFN is not defined` when I try to send alt+f2 for exmaple

Can you please tell me how those should look as I cannot find a solution for that?
Thank you!

**Comment by catborise** [comment]
i was working... okey i will check again

**Comment by Bandic007** [comment]
I made the fullscreen work but I had to move the fulscreen function from vnc lite file to yhe vnc base file script. However the same approach is not working with the function for the send ctrl alt fn krys as ot gives me that rfb is not defined when I move it in the vnc base. If I left them in vnc lite file they are not working at all.

**Comment by catborise** [comment]
okey i missed function keys to add for vnc.
it is working with spice but not vnc. i will correct it... thanks

**Comment by Bandic007** [comment]
This push uploaded some necessary files, but still when I clone your repo and try to use vnc I am getting:
Uncaught SyntaxError: The requested module '/static/js/novnc/core/rfb.js' does not provide an export named 'default' 
in the browser console and the VNC screen is stuck on loading.
Fulscreen button is not doing anything again, but it is also not throwing any errors in the browser console.\
Send ctrlAlt FN is again not working, but giving this error:
VM231:146 Uncaught ReferenceError: sendCtrlAltFN is not defined at HTMLLIElement.onclick (VM231:146)

Please, check!

**Comment by Bandic007** [comment]
Great, thank you! I will be waiting for the working version. I've downloaded and install with npm the latest version of noVNC from their repo already and it is working for me but after may tries I managed to make only the fulscreen button to work. The FN keys are still not working and I gave up on them, so I will be very grateful if you make it work out-of-the-box!
Thank you for the time you spend on this one!
Please, when you have some more time check on my request about the visual modifications that I suggested!

**Comment by Bandic007** [comment]
@catborise - any success fixing the noVNC issues?

**Comment by catborise** [comment]
it is fixed. it takes time to fix because of vacation. sorry. 
for now it should work.

**Comment by Bandic007** [comment]
Still not working for me for some reason. I will explain the case to you - I am using nginx as reverse proxy to get access to vns websocket over port 443. It is working with the initial old verision fo the retspen repo. It was even working when your first commit was borken and I used the novnc git version. But now after your commit from today it is not working. I did not changed anything it the way I am reverse proxying the websockets, it just wont work this time. I left with ome feeling that the novc app itself is not working as expected as the message this time is 1006 - connection closed. all times.
I am running over https strictly as I cannot test over port 80 http but I think it will be the same.
I order to reverse proxy the websockets I am injecting a location into the vnc url to active the proxy. This was working util today. However, I cannot see where the problem can be with nginx or even with the URL. Can you please double check if have not forget to commit something or add some files like last time? Are you able to test the VNC is working on your side also?

**Comment by catborise** [comment]
there is nothing much changed. novnc version is same like git version. i only add sending ctrl alt fn function...

you should check error with chrome tools(open vnc console page and right click to inspect) If there is an error it shows. 
Did you reload all javascripts with ctrl-f5 ?

**Comment by Bandic007** [comment]
Yes already checked with console of chrome. It gives several warnings but the only error is 1006 connection closed. I am able to telenet to port 6080 of the localhost which means that novnc is maybe running there but it wont open. Before I made my two rows of modifications to inject a location into the url for the proxying it was giving me error that cannot connect to this url and stuff, but after I did those same modifications I was using before it seems like connecting and being closed immediately.

**Comment by catborise** [comment]
can you please run the "novncd" with --debug --verbose..
firstly, stop novncd which is run with webvirtcloud . (kill it)
then start it with specified parameters.
example;
/srv/webvirtcloud/venv/bin/python /srv/webvirtcloud/console/novncd -d -v

then try to open console with web browser. check output of novncd, if there is anything unusual

**Comment by catborise** [comment]
does webvirtcloud run on a kvm host?

**Comment by catborise** [comment]
expected output example(webvirtcloud run on a vm);

/srv/webvirtcloud/venv/bin/python /srv/webvirtcloud/console/novncd -d -v
2018-08-28 10:33:43,621 - websocket.type - INFO : WebSocket server settings:
2018-08-28 10:33:43,621 - websocket.type - INFO :   - Listen on 0.0.0.0:6080
2018-08-28 10:33:43,621 - websocket.type - INFO :   - Flash security policy server
2018-08-28 10:33:43,621 - websocket.type - INFO :   - No SSL/TLS support (no cert file)
2018-08-28 10:33:43,622 - websocket.type - INFO :   - proxying from 0.0.0.0:6080 to ignore:ignore
2018-08-28 10:33:58,216 - websocket.type - DEBUG : 192.168.192.6: new handler Process
2018-08-28 10:33:58,309 - websocket.type - INFO : 192.168.192.6 - - [28/Aug/2018 10:33:58] "GET /websockify?token=4-2b1f7b9e-f95a-4e52-b997-e69fc6611131 HTTP/1.1" 101 -
2018-08-28 10:33:58,310 - websocket.type - INFO : 192.168.192.6 - - [28/Aug/2018 10:33:58] 192.168.192.6: Plain non-SSL (ws://) WebSocket connection
2018-08-28 10:33:58,310 - websocket.type - INFO : 192.168.192.6 - - [28/Aug/2018 10:33:58] 192.168.192.6: Version hybi-13, base64: 'False'
2018-08-28 10:33:58,311 - websocket.type - INFO : 192.168.192.6 - - [28/Aug/2018 10:33:58] 192.168.192.6: Path: '/websockify?token=4-2b1f7b9e-f95a-4e52-b997-e69fc6611131'
2018-08-28 10:33:58,339 - root - DEBUG : Connection infos :
- connhost : '10.20.30.108'
- connport : '22'
- connuser : 'webvirtmgr'
- conntype : '1'
- console_host : '0.0.0.0'
- console_port : '5911'
- console_socket : 'None'

2018-08-28 10:33:58,340 - websocket.type - INFO : 192.168.192.6 - - [28/Aug/2018 10:33:58] connecting to: 10.20.30.108:5911

Traffic Legend:
    }  - Client receive
    }. - Client receive partial
    {  - Target receive

    >  - Target send
    >. - Target send partial
    <  - Client send
    <. - Client send partial

**Comment by Bandic007** [comment]
Yes it is running on the KVM host and I even have some VMs with VNC ports there.
Strange is when I deploy the original retspen version of vnc  the same config with the same proxing over 443 is working fine and the console is opening fine.

**Comment by catborise** [comment]
yes, strange it is.
i made tests with two different webvirtcloud installation, there is not any problem. it is working smootly.

problem key statement is: websocket.type - INFO : 192.168.1.125 - - [28/Aug/2018 07:16:56] Need a tunnel to access console but can't mount one because it's not a SSH host

**Comment by catborise** [comment]
could you check it with spice?

open virt-manager. select any vm, enter configuration. 
![image](https://user-images.githubusercontent.com/1725643/44709101-7d204400-aab1-11e8-9b5c-db1d139d1fbf.png)

change vnc to spice server.
make video vga
(it is required shutdown vm and start it again after changes)

**Comment by Bandic007** [comment]
I will try but I need some more time to set it up.
However - I think for some reason despite starting the novnc with /srv/webvirtcloud/console/novncd it is not taking the settings there.
I've made a test and changed some setting in this file - like connhost and cert and other and despite I've changed it it is still starting with the same settings as before and obviously not working as expected.
Example is that I've changed connhost which is set to be the same as WS_HOST directly to "0.0.0.0" but it is still telling me that connhost is "localhost" not 0.0.0.0

`2018-08-28 08:02:19,641 - root - DEBUG : Connection infos :
- connhost : 'localhost'
- connport : '22'
- connuser : 'qemu'
- conntype : '1'
- console_host : '127.0.0.1'
- console_port : '5901'
- console_socket : 'None'`

**Comment by Bandic007** [comment]
I think this guy is describing something similar but there is no fix described:
https://github.com/retspen/webvirtmgr/issues/595

**Comment by Bandic007** [comment]
I've made it work, but I have a strange behaviour now.
The VM xml was configure to listen for VNC to 127.0.0.1
I've changed that to 0.0.0.0 and it worked and now it is opening the console.
It is just strange as it is opening like 2 console windows in the same html page one under the another.
I am attaching a picture to get what I am saying. I've zoomed out the browser so that the two windows can be visible.
DO you have any idea why this is hapnening and how can it be fixed? Something in the HTML or?

**Comment by catborise** [comment]
i think there is a problem with novncd . 
some time ago i fix some exception messages. may be it is related with that. can you find older version to try it again. 
beside that i think i find your error is related with console_host.
your "console_host" = 127.0.0.1 and it causes that error.
you can change it from vm xml (127.0.0.1 -> 0.0.0.0)
or enable vnc listen from:
/etc/libvirt/qemu.conf
  vnc_listen = "0.0.0.0"
  spice_listen = "0.0.0.0"
`sed -i 's/#vnc_listen/vnc_listen/g' /etc/libvirt/qemu.conf
sed -i 's/#spice_listen/spice_listen/g' /etc/libvirt/qemu.conf`
then restart libvirt(it is safe to restart)
-----------------
i think it is resolved with console/view.py modification of specified issue
`ws_port = console_websocket_port if console_websocket_port else WS_PORT
 ws_host = WS_PUBLIC_HOST if WS_PUBLIC_HOST else request.get_host()` 

in the view.py it tries to get websocket port from vm config. if it is not specified with vm config it sets default one which is 6080(settings.py)
--------------

**Comment by Bandic007** [comment]
Yes, great! It solves the issue. I just need to set my VMs to listen to 0.0.0.0 in xml!
And what about the two console screens in the html that are opening?
I've attached a screenshot above.

**Comment by catborise** [comment]
whats that :))))))))))))))))) mine is like that. i havent noticed before 👍 
i am checking now :) it is hillarious

**Comment by catborise** [comment]
by the way, can you please check vnc console from instance details i add full vnc console option to vm.
enter instance detail -> access -> console-dropdown -> console-full

**Comment by Bandic007** [comment]
I cannot see such option in my setup. But my setup is kind of a big mix. However, I am using your HTMLs for console, but I am not sure I use them for instance details.
Can you give me refenrece where the change is

**Comment by Bandic007** [comment]
@catborise I was able to find the html where you expose this functionality and added it to  my setup but full console is opening and not working.
It gives me failed to connect to server.

**Comment by Bandic007** [comment]
@catborise man. it is working. My mistake - I've fogot to add the value for the proxy path to the URL of the full vnc html file. I've done this and it is working like a charm now.
So - the only problem here is to fix the two screens in the vnc lite html 
Found anything related to it?

**Comment by catborise** [comment]
because of specified script it calls a function twice. so it produces two same console app. 
loader.src = "{% static "js/novnc/vendor/browser-es-module-loader/dist/browser-es-module-loader.js" %}";

in vnc-lite.html, specified script statement should be true...
<script type="module"> window._noVNC_has_module_support = false;</script>

i am committing now.

**Comment by Bandic007** [comment]
@catborise - you are great man!
Thanks, everything is working as expected now!
I guess you can open a merge request to the master repo now!
I am closing the issue!
